# Welcome to `ignite.toml`.
#
# Since we're running gluegun in branded mode with `ignite`,
# this is the file that will be loaded, not `gluegun.toml`
# any more.

# where can we find the plugins for this project? 
plugins = [
  '../../sample-ignite-generators'
]

# these are the new default values for the ignite plugin
[defaults.ignite]
tests          = 'ava'  # use AVA-based tests
askToOverwrite = true   # don't prompt when overwriting existing files
