/**
 * This file cleans up the build artifacts generated by createDirect.js.
 */

const directFiles = ['toolbox', 'filesystem', 'strings', 'print', 'system', 'semver', 'http', 'patching', 'prompt']
const fs = require('fs')
directFiles.forEach(f => fs.unlinkSync(__dirname + '/../' + f + '.js'))
