/**
 * This file cleans up the build artifacts generated by createDirect.js.
 */

const directFiles = [
  'filesystem',
  'strings',
  'print',
  'system',
  'semver',
  'http',
  'patching',
  'prompt',
  'package-manager',
]
const fs = require('fs')
directFiles.forEach(f => {
  const filename = __dirname + '/../' + f + '.js'
  if (fs.existsSync(filename)) fs.unlinkSync(filename)
})
